name: container
on:
  push:
    branches:
      - gh-pages
  pull_request:
  
jobs:
  podman:
    name: podman
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
      - name: Get source
        uses: actions/checkout@v3
      - name: Create container
        run: |
          ./build.sh
